name:                openapi-refactor
version:             0.1.0.0
github:              "githubuser/openapi-refactor"
license:             BSD3
author:              "Francisco Chaves"
maintainer:          "pachopepe@gmail.com"
copyright:           "2019 Francisco Chaves"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/openapi-refactor#readme>

dependencies:
- base >= 4.7 && < 5
- yaml >= 0.11 && < 0.12
- HsYAML >= 0.1.2 && <= 0.3
- containers >= 0.6 && < 0.7
- text >= 1.2 && < 1.3
- aeson >= 1.4 && < 1.5
- unordered-containers >= 0.2 && < 0.3

library:
  source-dirs: src

executables:
  openapi-refactor-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - openapi-refactor

tests:
  openapi-refactor-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - openapi-refactor
